"""
Radio RCA Rules and Constants.

Thresholds, time windows, and event type enums for radio detection rules.
"""

# Time windows for correlation (seconds)
CORRELATION_WINDOW_TIGHT = 5.0
CORRELATION_WINDOW_MEDIUM = 10.0
CORRELATION_WINDOW_WIDE = 20.0

# RF KPI Thresholds
RSRP_POOR_THRESHOLD = -110.0    # dBm — poor coverage
RSRP_CRITICAL_THRESHOLD = -120.0  # dBm — edge of coverage
RSRQ_POOR_THRESHOLD = -15.0     # dB
SINR_POOR_THRESHOLD = 0.0       # dB
SINR_CRITICAL_THRESHOLD = -3.0  # dB
CQI_POOR_THRESHOLD = 5
BLER_HIGH_THRESHOLD = 10.0      # percent
THROUGHPUT_COLLAPSE_THRESHOLD = 100.0  # kbps — near-zero throughput
HARQ_NACK_CRITICAL_THRESHOLD = 10.0   # percent — critical RF limit

# Finding types
class RadioFindingType:
    RADIO_LINK_FAILURE_IMPACTING_CALL = "RADIO_LINK_FAILURE_IMPACTING_CALL"
    HANDOVER_FAILURE_OR_SRVCC = "HANDOVER_FAILURE_OR_SRVCC"
    PAGING_FAILURE_OR_UE_UNREACHABLE = "PAGING_FAILURE_OR_UE_UNREACHABLE"
    COVERAGE_DEGRADATION = "COVERAGE_DEGRADATION"
    RADIO_DATA_PATH_DEGRADATION = "RADIO_DATA_PATH_DEGRADATION"
    RRC_REESTABLISHMENT_DETECTED = "RRC_REESTABLISHMENT_DETECTED"
    RRC_RECONFIGURATION_FAILURE = "RRC_RECONFIGURATION_FAILURE"
    RRC_RECONFIGURATION_LATENCY = "RRC_RECONFIGURATION_LATENCY"
    ABNORMAL_RADIO_RELEASE = "ABNORMAL_RADIO_RELEASE"
    ERAB_SETUP_FAILURE = "ERAB_SETUP_FAILURE"
    SGNB_ADDITION_FAILURE = "SGNB_ADDITION_FAILURE"
    HIGH_HARQ_NACK_RATIO = "HIGH_HARQ_NACK_RATIO"
    CSFB_DETECTED = "CSFB_DETECTED"
    NOT_OBSERVABLE = "NOT_OBSERVABLE"

# Events considered critical for call impact
CALL_IMPACTING_EVENTS = ["RLF", "HO_FAIL", "RRC_REESTABLISHMENT"]
MOBILITY_EVENTS = ["HO_ATTEMPT", "HO_SUCCESS", "HO_FAIL", "CSFB", "SRVCC"]
